/*
 * File: app/view/InformarErro.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.InformarErro', {
    extend: 'Ext.form.Panel',
    alias: 'widget.informarErro',

    config: {
        id: 'informarerro',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                hidden: true,
                id: 'toolbarInformarErro',
                title: 'Informar Erro'
            },
            {
                xtype: 'fieldset',
                id: 'erroOrigem',
                style: 'margin-top:-20px;',
                title: 'Origem',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'selectErroOrigem',
                        itemId: 'myselectfield',
                        value: 'Selecionadorrr',
                        options: [
                            {
                                text: 'Selecione',
                                value: -1
                            },
                            {
                                text: 'Linha',
                                value: 1
                            },
                            {
                                text: 'Ponto',
                                value: 2
                            },
                            {
                                text: 'Onibus',
                                value: 3
                            },
                            {
                                text: 'Empresa',
                                value: 4
                            },
                            {
                                text: 'Ubibus',
                                value: 5
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        hidden: true,
                        id: 'txtErrodentificador',
                        placeHolder: 'Identificador'
                    }
                ]
            },
            {
                xtype: 'label',
                hidden: true,
                html: 'Título: informação!',
                id: 'lblInformacaoErro',
                style: 'text-align:center;font-style:italic;'
            },
            {
                xtype: 'textareafield',
                height: 236,
                id: 'txtDescricaoOcorrencia1',
                placeHolder: 'Descriçao do Erro'
            },
            {
                xtype: 'button',
                id: 'btnErroRegistrar',
                itemId: 'mybutton22',
                style: 'margin-top:-20px;',
                text: 'Registrar'
            }
        ],
        listeners: [
            {
                fn: 'onSelectErroOrigemChange',
                event: 'change',
                delegate: '#selectErroOrigem'
            },
            {
                fn: 'onBtnOcorrenciaRegistrarTap',
                event: 'tap',
                delegate: '#btnErroRegistrar'
            },
            {
                fn: 'onFormpanelActivate',
                event: 'activate'
            }
        ]
    },

    onSelectErroOrigemChange: function(selectfield, newValue, oldValue, eOpts) {
        var txtIdentidicador = Ext.getCmp('txtOcorrenciaIdentificador');

        txtIdentidicador.setValue('');

        switch(newValue){
            case 1: //Linha
            txtIdentidicador.setHidden(false);
            txtIdentidicador.setPlaceHolder('nº da linha');
            break;

            case 2: //Ponto
            txtIdentidicador.setHidden(false);
            txtIdentidicador.setPlaceHolder('nº do ponto / referência');
            break;

            case 3: //Onibus
            txtIdentidicador.setHidden(false);
            txtIdentidicador.setPlaceHolder('nº do onibus');
            break;

            case 4: //Empresa
            txtIdentidicador.setHidden(false);
            txtIdentidicador.setPlaceHolder('nome da empresa');
            break;

            case 5: //Ubibus
            txtIdentidicador.setHidden(true);
            txtIdentidicador.setPlaceHolder('');
            txtIdentidicador.setValue('');
            break;

            default:
            txtIdentidicador.setHidden(true);

        }
    },

    onBtnOcorrenciaRegistrarTap: function(button, e, eOpts) {
        Ext.Msg.confirm(
        "Confirmação",
        "Deseja registrar esta ocorrência?",
        function(buttonId) {
            if(buttonId === 'yes') {
                Ext.Msg.alert('Obrigado', 'Sua ocorrência foi registrada com sucesso!', Ext.emptyFn);

                Ext.getCmp('selectOcorrenciaOrigem').setValue(-1);

                Ext.getCmp('ocorrencia').reset();
            }
        }, 
        this // scope of the controller 
        );


    },

    onFormpanelActivate: function(container, newActiveItem, oldActiveItem, eOpts) {
        Ext.getCmp('toolbarOcorrencia').setHidden(false);
        Ext.getCmp('lblInformacaoOcorrencia').setHidden(true);
        Ext.getCmp('ocorrenciaOrigem').setHidden(false);
    }

});