/*
 * File: app/view/Usuario.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ubibus.view.Usuario', {
    extend: 'Ext.form.Panel',
    alias: 'widget.usuario',

    config: {
        id: 'usuario',
        store: 'usuarios',
        layout: {
            type: 'vbox'
        },
        items: [
			{
                xtype: 'label',
                html: '',
                id: 'lblUsuarioStatus',
                style: 'text-align:center;margin-top:-10px;font-style: italic;'
            },   
            {
                xtype: 'segmentedbutton',
                id: 'opcoesUsuario',
                itemId: 'mysegmentedbutton4',
                ui: 'round',
                allowDepress: false,
                layout: {
                    align: 'start',
                    pack: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        pressed: true,
                        id: 'UsuarioLogar',
                        text: 'Login'
                    },
                    {
                        xtype: 'button',
                        id: 'UsuarioCadastrar',
                        text: 'Cadastro'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Dados',
                items: [
                    {
                        xtype: 'textfield',
                        hidden: true,
                        id: 'txtUsuarioNome',
                        placeHolder: 'Nome'
                    },
                    {
                        xtype: 'textfield',
                        id: 'txtUsuarioEmail',
                        placeHolder: 'E-mail'
                    },
                    {
                        xtype: 'passwordfield',
                        id: 'txtUsuarioSenha',
                        placeHolder: 'Senha'
                    },
                    {
                        xtype: 'passwordfield',
                        hidden: true,
                        id: 'txtUsuarioConfirmarSenha',
                        label: '',
                        placeHolder: 'Confirmar senha'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'btnUsuarioLogar',
                style: 'margin-top:-20px;',
                ui: 'confirm',
                text: 'Logar'
            },
            {
                xtype: 'button',
                hidden: true,
                id: 'btnUsuarioCadastrar',
                style: 'margin-top:-20px;',
                ui: 'confirm',
                text: 'Cadastrar'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Usuários'
            },
            {
                xtype: 'spacer',
                height: 20
            }
        ],
        listeners: [
            {
                fn: 'onOpcoesUsuarioToggle',
                event: 'toggle',
                delegate: '#opcoesUsuario'
            }
        ]
    },

    onOpcoesUsuarioToggle: function(segmentedbutton, button, isPressed, eOpts) {
        switch(button.id)
        {
            case 'UsuarioLogar':
            Ext.getCmp('txtUsuarioNome').setHidden(true);
            Ext.getCmp('txtUsuarioConfirmarSenha').setHidden(true);
            Ext.getCmp('btnUsuarioLogar').setHidden(false);
            Ext.getCmp('btnUsuarioCadastrar').setHidden(true);
            //Ext.getCmp('btnUsuarioConfirmar').setText('Logar');

            break;

            case 'UsuarioCadastrar':
            Ext.getCmp('txtUsuarioNome').setHidden(false);
            Ext.getCmp('txtUsuarioConfirmarSenha').setHidden(false);
            Ext.getCmp('btnUsuarioLogar').setHidden(true);
            Ext.getCmp('btnUsuarioCadastrar').setHidden(false);
            //Ext.getCmp('btnUsuarioConfirmar').setText('Cadastrar');

            break;

            default:         
        }
    }

});